### ISSUE TITLE
Creating jail doesn't work in FreeNAS 11.1-U4

### ISSUE THREAD

**Issue by danb35** [danb35/freenas-iocage-nextcloud#10]

**Comment by danb35** [comment]
Multiple users are reporting a python traceback reporting network issues:
```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 145, in cli
    basejail=basejail, empty=empty)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 644, in create
    exit_on_error=self.exit_on_error).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 86, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 445, in _create_jail
    self.create_install_packages(jail_uuid, location, config)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 488, in create_install_packages
    silent=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 64, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 127, in __start_jail__
    vnet_interfaces = self.conf["vnet_interfaces"]
KeyError: 'vnet_interfaces'
```

**Comment by danb35** [comment]
Reported this as FreeNAS issue #30672, which is marked private due to the attached debug file.

**Comment by Tim-ofzo** [comment]
Issue is fixed by using newest version of iocage. See [this commit](https://github.com/iocage/iocage/commit/0271b76d46767def4d9085f88edf30e726e28733)
Execute the following to update iocage and make the script work again. 
`cd /tmp
git clone --recursive https://github.com/iocage/iocage
cp -R iocage/iocage/lib/ /usr/local/lib/python3.6/site-packages/iocage/lib
`

**Comment by danb35** [comment]
Temporary workaround in #11
