### ISSUE TITLE
Error when trying to access nextcloud

### ISSUE THREAD

**Issue by MHOOO** [danb35/freenas-iocage-nextcloud#33]
So I've installed nextcloud on my Freenas 11.1-U2 box and according to the Script everything went just fine.
However when I try to access the web-page of nextcloud I get: 
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

The nextcloud.log prints:
`[Sat May 12 22:23:40.787327 2018] [proxy_fcgi:error] [pid 48700:tid 34399133952] [client 192.168.1.9:52932] AH01071: Got error 'PHP message: {"reqId":"b458QqKvjA3ddhdpYgWR","level":3,"time":"2018-05-12T22:23:40+02:00","remoteAddr":"192.168.1.9","user":"--","app":"index","method":"GET","url":"\\/favicon.ico","message":"Exception: {\\"Exception\\":\\"OCP\\\\\\\\AppFramework\\\\\\\\QueryException\\",\\"Message\\":\\"Could not resolve clientService! Class clientService does not exist\\",\\"Code\\":0,\\"Trace\\":\\"#0 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/AppFramework\\\\\\/Utility\\\\\\/SimpleContainer.php(118): OC\\\\\\\\AppFramework\\\\\\\\Utility\\\\\\\\SimpleContainer->resolve('clientService')\\\\n#1 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/ServerContainer.php(132): OC\\\\\\\\AppFramework\\\\\\\\Utility\\\\\\\\SimpleContainer->query('clientService')\\\\n#2 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/AppFramework\\\\\\/Utility\\\\\\/SimpleContainer.php(74): OC\\\\\\\\ServerContainer->query('clientService')\\\\n#3 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\...\nPHP message: {"reqId":"b458QqKvjA3ddhdpYgWR","level":3,"time":"2018-05-12T22:23:40+02:00","remoteAddr":"192.168.1.9","user":"--","app":"core","method":"GET","url":"\\/favicon.ico","message":"Exception: {\\"Exception\\":\\"OCP\\\\\\\\AppFramework\\\\\\\\QueryException\\",\\"Message\\":\\"Could not resolve clientService! Class clientService does not exist\\",\\"Code\\":0,\\"Trace\\":\\"#0 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/AppFramework\\\\\\/Utility\\\\\\/SimpleContainer.php(118): OC\\\\\\\\AppFramework\\\\\\\\Utility\\\\\\\\SimpleContainer->resolve('clientService')\\\\n#1 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/ServerContainer.php(132): OC\\\\\\\\AppFramework\\\\\\\\Utility\\\\\\\\SimpleContainer->query('clientService')\\\\n#2 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/AppFramework\\\\\\/Utility\\\\\\/SimpleContainer.php(74): OC\\\\\\\\ServerContainer->query('clientService')\\\\n#3 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/...\nPHP message: {"reqId":"b458QqKvjA3ddhdpYgWR","level":3,"time":"2018-05-12T22:23:40+02:00","remoteAddr":"192.168.1.9","user":"--","app":"core","method":"GET","url":"\\/favicon.ico","message":"Exception: {\\"Exception\\":\\"RedisException\\",\\"Message\\":\\"Redis server went away\\",\\"Code\\":0,\\"Trace\\":\\"#0 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/Memcache\\\\\\/Redis.php(103): Redis->setnx('d91775ed7b26f6e...', 0)\\\\n#1 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/Lock\\\\\\/MemcacheLockingProvider.php(77): OC\\\\\\\\Memcache\\\\\\\\Redis->add('files\\\\\\/10223877d...', 0)\\\\n#2 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/Files\\\\\\/Storage\\\\\\/Common.php(709): OC\\\\\\\\Lock\\\\\\\\MemcacheLockingProvider->acquireLock('files\\\\\\/10223877d...', 2)\\\\n#3 \\\\\\/usr\\\\\\/local\\\\\\/www\\\\\\/apache24\\\\\\/data\\\\\\/nextcloud\\\\\\/lib\\\\\\/private\\\\\\/Files\\\\\\/Storage\\\\\\/Wrapper\\\\\\/Wrapper.php(592): OC\\\\\\\\Files\\\\\\\\Storage\\\\\\\\Common->acquireLock('scanner::appdat.....\n', referer: https://192.168.1.115/
`

I am unable to find any problems regarding clientService via google, so I'm sorta out of ideas on how to debug this.
Any hints?

**Comment by MHOOO** [comment]
I successfully fixed the issue by adding:
```
  'redis' => array (
    'host' => '/tmp/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
),
```
into nextcloud's config/config.php
